### ISSUE TITLE
Does this work with ZF3?

### ISSUE THREAD

**Issue by ghost** [netiul/DOMPDFModule#1]
Hello ,
I just need to confirm if dompdf works with zf3.

Thanks and regards,
Prashant Kasajoo

**Comment by BrunoSpy** [comment]
A quick look at composer.json : 

```
"zendframework/zend-eventmanager": "^2.3",
"zendframework/zend-servicemanager": "^2.3",
"zendframework/zend-view": "^2.3"
```

Doesn't seem to be compatible.

**Comment by zluiten** [comment]
@ghost @BrunoSpy I've added support for zf3 finally :-)
